# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'JDNetWorkManagerDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
#  use_frameworks!
  pod 'JDNetWorkManager', :path => '../JDNetWorkManager.podspec'  #指定podspec文件


  # Pods for JDNetWorkManagerDemo

  target 'JDNetWorkManagerDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'JDNetWorkManagerDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
